name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #BASE_TOOLS
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  photo_view: ^0.14.0
  #FRONT_END_TOOLS
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.6
  auto_size_text: ^3.0.0

  #BACK_END_TOOLS
  equatable: ^2.0.5
  get_it: ^7.2.0
  auto_route: ^5.0.2
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  google_sign_in: ^5.4.2
  firebase_auth: ^4.1.1
  onesignal_flutter: ^3.4.2
  flutter_local_notifications: ^12.0.3
  http:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
